"""change user id to uuid

Revision ID: 51ddc645ddc5
Revises: 0bdc0528996a
Create Date: 2025-10-08 22:32:44.150148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51ddc645ddc5'
down_revision: Union[str, Sequence[str], None] = '0bdc0528996a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS users CASCADE")
    op.execute("DROP TYPE IF EXISTS user_role_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS user_status_enum CASCADE")
    op.execute("DROP TYPE IF EXISTS activity_type_enum CASCADE")
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fullName', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'ADMIN', name='user_role_enum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'BLOCKED', name='user_status_enum'), nullable=False),
    sa.Column('registrationDate', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    # ### end Alembic commands ###
